using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class BotnetTier2Manager : MonoBehaviour {
    public float botnetPointPerSecond;
    public int numberOfUpgrades;
    public float numberOfBotnets;
    public double totalPointsPerSecond;
    public double basePointsToLose;
    public double totalPointsToLose;

    public int baseCost;
    public int currentCost;
    public int upgradeCost;
    public int maxUpgrade;

    [Range(0f, 1f)]
    public float percentToGetCaught;
    [Range(0f, 1f)]
    public float minPercentToGetCaught;

    private bool coroutineSwitch;

    //UI stuff
    public Text numberOfBotnetsUIValue;
    public Text costOfBotnetUIValue;
    public Text numberOfUpgradesUIValue;
    public Text costOfUpgradeUIValue;

    public Button buyButton;
    public Button upgradeButton;

    //GameManager reference
    private GameObject GM;
    private GameObject STM;

    void Start()
    {
        GM = GameObject.Find("GameManager").gameObject;
        STM = GameObject.Find("ServerTierManager").gameObject;
        coroutineSwitch = false;
        currentCost = baseCost;
        totalPointsToLose = basePointsToLose;
    }

    void Update()
    {
        //change points per second by botnets
        totalPointsPerSecond = numberOfBotnets * botnetPointPerSecond + numberOfBotnets * botnetPointPerSecond * STM.GetComponent<ServerTierManager>().serverTier;
        //change UI for number of botnets
        numberOfBotnetsUIValue.text = Convert.ToInt32(numberOfBotnets).ToString();
        //change UI for cost of botnets
        ShowUICost(costOfBotnetUIValue, currentCost);
        //change UI for number of upgrades
        numberOfUpgradesUIValue.text = numberOfUpgrades.ToString();
        //change UI for cost of upgrades
        ShowUICost(costOfUpgradeUIValue, upgradeCost);
        //if player points < cost, disable button
        if (GM.GetComponent<ScoreManager>().points < currentCost)
        {
            buyButton.interactable = false;
        }
        else
        {
            buyButton.interactable = true;
        }

        if (GM.GetComponent<ScoreManager>().points < upgradeCost)
        {
            upgradeButton.interactable = false;
        }
        else
        {
            upgradeButton.interactable = true;
        }
    }

    IEnumerator BotnetPointGiver()
    {
        yield return new WaitForSeconds(1 / numberOfBotnets);
        while (true)
        {
            float percentCatch = UnityEngine.Random.value;
            //check to see if player is caught
            if (percentCatch <= 1 - percentToGetCaught)
            {
                //give player points generated by botnet
                GM.GetComponent<ScoreManager>().points += botnetPointPerSecond + botnetPointPerSecond * STM.GetComponent<ServerTierManager>().serverTier;
            }
            else
            {
                Debug.Log("you are caught!");
                //reset all botnets
                numberOfBotnets = 0;
                //reset cost of botnets
                currentCost = baseCost;
                //reset coroutine switch
                coroutineSwitch = false;
                //reset points to lose
                totalPointsToLose = basePointsToLose;
                //take away player's points
                GM.GetComponent<ScoreManager>().points -= totalPointsToLose;
                //break out of coroutine loop
                break;
            }
            //wait X seconds before giving player points generated by botnet where X is 1/number of botnets
            yield return new WaitForSeconds(1 / numberOfBotnets);
        }
    }

    public void IncreaseNumberOfBotnets()
    {
        //checks if the player has enough points to buy a botnet
        if (GM.GetComponent<ScoreManager>().points >= currentCost)
        {
            //decrease player's points by 1 botnet cost
            GM.GetComponent<ScoreManager>().points -= currentCost;
            //increase player's number of botnets
            numberOfBotnets += 1;
            //increase total points to lose
            totalPointsToLose *= numberOfBotnets;
            //increase cost of botnet everytime it is purchased
            currentCost = Convert.ToInt32(baseCost * Mathf.Pow(1.15f, numberOfBotnets));
        }
        //activates coroutine only once; when player gets first botnet
        if (coroutineSwitch == false)
        {
            StartCoroutine(BotnetPointGiver());
            coroutineSwitch = true;
        }
    }

    public void IncreaseNumberOfUpgrades()
    {
        // checks if the player has enough points to upgrade
        if (GM.GetComponent<ScoreManager>().points >= upgradeCost)
        {
            //decrease player's points by 1 botnet cost
            GM.GetComponent<ScoreManager>().points -= currentCost;
            //increase player's number of botnets
            numberOfUpgrades += 1;
            //increase botnet point per second
            botnetPointPerSecond = botnetPointPerSecond * 2;
            //reduce percent change to get caught
            if (percentToGetCaught > minPercentToGetCaught)
            {
                percentToGetCaught /= 2;
            }
            else if (percentToGetCaught < minPercentToGetCaught)
            {
                percentToGetCaught = minPercentToGetCaught;
            }
            //max level of upgrades
            if (numberOfUpgrades == maxUpgrade)
            {
                upgradeButton.interactable = false;
                upgradeCost = 0;
            }
            else
            {
                //increase cost of upgrade everytime it is purchased
                upgradeCost = Convert.ToInt32(upgradeCost * 5);
            }
        }
    }

    //UI stuff
    public void ShowUICost(Text myText, int myCost)
    {
        myText.text = " Cost: " + myCost.ToString();
    }
}